# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revisi_PI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_nilai',
            name='berat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='import_nilai',
            name='nilai',
            field=models.FloatField(null=True),
        ),
    ]
