# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Revisi_PI', '0002_auto_20170511_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regresi_korelasi',
            old_name='post_id',
            new_name='post',
        ),
    ]
